### ISSUE TITLE
Network throughput between two RPi 3B running RF24GatewayNode.

### ISSUE THREAD

**Issue by lukolszewski** [TMRh20/RF24Gateway#21]
What realistic data rate one should expect when running RF24GatewayNode on two RPis sitting on the same desk? I'm only getting about 15kB/s (I tried 1MBPS and 2MBPS data rates on various channels). This is using the cheap nrf24l01 PA+LNA boards connected to RPi GPIO with 15cm long wires. SPI speed was left as is (10MHz).

Similar speeds were observed with TCP as well as UDP traffic.

Should I be looking at soldering extra filtering caps on my nrf adapters, or are there some additional software tweaks I can do to speed it up. I have to admit I was hoping for close to 100kB/s whe using 2MBPS data rate. Is this achievable?

EDIT: I have also soldered an extra 10uF tantalum cap to both nRF devices as describer elsewhere. Additionally I did try using the interrupt version of the code. This run with peak speed of about 30kB/s. This was the same with 1MBPS as well as 2MBPS settings. I also tried lowering SPI frequency (it only slowed things down) as well as lowering the power. 30kB/s was the best I got (1m distance).

**Comment by TMRh20** [comment]
Yeah, it sounds like you've maxed out the parameters of the devices.
In practice, at the core RF24 layer, the radios can just about hit the max data rate, but that is using one-way communication only. Sending 32 bytes is 1-2mbit, but more than 32 bytes there are some delays, so lop off 10-20% speed.
Then as soon as you involve auto-ack, (ESB) functionality, cut that data rate in a bit more than half.
Then the RF24Network layer has a header of 8-bytes, so cut off another 25%.
Then the TCP/IP layer has some overhead too, so lop off another bit.
What you are left with is about 25-30KB/s data rate at the RF24Gateway layer. (~200Kbps)
If you have a routing node in between the two RPi, then it drops down even further to 3-5KB/s.

All in all it is a trade-off between functionality and speed. For max data-rate, between two devices, you would have to transmit at a lower layer in the RF24 stack, but you lose the functionality of fragmentation/reassembly and TCP/IP etc...

Interesting you thought to use interrupts, that is one of the ways to get the most performance out of these devices on RPi.

Since these are digital devices, the 30KB/s should hold even over a good distance, but that is about the max.
